name: Create PDFs
on:
  push:
    branches:
      - main
      - features/autodeploy

jobs:
  Publish-Cookbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download emerald font
        run: |
          curl -OL https://mirrors.ctan.org/fonts/emerald.zip
          unzip emerald.zip

      - name: Create PDFs
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: MyCookbook.tex
        env:
          TEXINPUTS: ".:./emerald//:"

      - name: Create deploy directory
        run: mkdir deploy
      
      - name: Copy Cookbook
        uses: canastro/copy-file-action@master
        with:
          source: "MyCookbook.pdf"
          target: "deploy/MyCookbook.pdf"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy