name: Create PDFs
on:
  push:
    branches:
      - main

jobs:
  Publish-Cookbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add curl
            curl -OL https://mirrors.ctan.org/fonts/emerald.zip
            unzip emerald.zip
            cp -a ./emerald/. /opt/texlive/texmf-local/
            mktexlsr
            updmap-sys --force --enable Map=emerald.map
            mktexlsr
            pdflatex -synctex=1 -interaction=nonstopmode "./MyCookbook".tex
            pdflatex -synctex=1 -interaction=nonstopmode "./MyCookbook".tex
      
      - name: Copy Cookbook
        uses: canastro/copy-file-action@master
        with:
          source: "MyCookbook.pdf"
          target: "deploy/MyCookbook.pdf"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy